using System.Collections;
using System.Globalization;

namespace XlsxSharp.Parser.Tests;

public class NameUtilsTests
{
    [Test]
    [Arguments("A", false)] // First char - Letter-like
    [Arguments("Z", false)]
    [Arguments("㝳", false)]
    [Arguments("㏝", false)]
    [Arguments(" ", true)] // First char - non-letter-like
    [Arguments(".", true)]
    [Arguments("^", true)]
    [Arguments("!", true)]
    [Arguments("+", true)]
    [Arguments("0", true)]
    [Arguments("㏞", true)]
    [Arguments("😁", true)] // Symbol, non base multilingual plane
    [Arguments("AZ", false)] // Subsequent char - letter-like
    [Arguments("A0", false)] // Subsequent char - number-like
    [Arguments("A.", false)] // Subsequent char - symbol-like
    [Arguments("A!", true)] // Subsequent char - other
    [Arguments("A+A", true)]
    [Arguments("A😁", true)]
    public async Task NameShouldBeQuotedWhenFirstCharIsLetterAndRestLetterNumberOrSymbol(
        string sheetName,
        bool shouldBeQuoted
    )
    {
        await Assert.That(NameUtils.ShouldQuote(sheetName)).IsEqualTo(shouldBeQuoted);
    }

    [Test]
    public async Task EmptyNameIsNotValidSheetName()
    {
        await Assert.That(NameUtils.IsSheetNameValid(string.Empty)).IsFalse();
    }

    [Test]
    public async Task SheetNameCanHaveAtMost31Chars()
    {
        await Assert.That(NameUtils.IsSheetNameValid(new string('A', 31))).IsTrue();
        await Assert.That(NameUtils.IsSheetNameValid(new string('A', 32))).IsFalse();
    }

    [Test]
    [Arguments("*", false)]
    [Arguments("/", false)]
    [Arguments(":", false)]
    [Arguments("?", false)]
    [Arguments("[", false)]
    [Arguments("\\", false)]
    [Arguments("]", false)]
    [Arguments("name", true)]
    [Arguments(" ", true)]
    public async Task SheetNameWithoutForbiddenChars(string name, bool isValid)
    {
        await Assert.That(NameUtils.IsSheetNameValid(name)).IsEqualTo(isValid);
    }

    [Test]
    [Skip("Used to generate bitmask for the quotation.")]
    [Arguments(@"ident-sheet-first.txt")]
    [Arguments(@"ident-sheet-next.txt")]
    public void GenerateSheetQuotationData(string path)
    {
        // Files were generated by AutoHotKey script that changed the name of a sheet and checked formula
        // referencing the sheet. There is no obvious pattern. Codepoints from Unicode 5.2+ are always quoted,
        // at least for BMP. Other than that, MS folk creativity at work.
        // The invalid code points for sheet name are not in the file: * 2A,/ 2F,: 3A,? 3F,[ 5B,\ 5C,] 5D
        BitArray codepointQuoted = new(0x10000);
        foreach (string line in File.ReadAllLines(path))
        {
            int codepoint = int.Parse(line[..4], NumberStyles.HexNumber);
            bool isQuoted = line[5..] switch
            {
                "YES" => true,
                "NO" => false,
                _ => throw new NotSupportedException(line),
            };
            codepointQuoted[codepoint] = isQuoted;
        }

        int[] intArray = new int[65536 / 32];
        codepointQuoted.CopyTo(intArray, 0);
        TestContext.Current!.Output.WriteLine(
            string.Join(", ", intArray.Select(x => "0x" + x.ToString("X8")))
        );
    }

    [Test]
    [Arguments("name", true)]
    [Arguments("_name", true)]
    [Arguments("\\name", true)] // A leading backslash is allowed (matches the Rolex NAME regex).
    [Arguments("name1", true)] // Digits are allowed after the first character.
    [Arguments("A01", true)] // Not a valid reference, but still a validly-shaped name.
    [Arguments("my.name", true)] // Periods are allowed after the first character.
    [Arguments("my_name", true)]
    [Arguments("my\\name", true)]
    [Arguments("my?name", true)] // Question marks are allowed after the first character.
    [Arguments("", false)]
    [Arguments("1name", false)] // Can't start with a digit.
    [Arguments(".name", false)] // Can't start with a period.
    [Arguments("?name", false)] // Can't start with a question mark, unlike after the first char.
    [Arguments("my name", false)] // No spaces.
    [Arguments("my!name", false)]
    public async Task NameIsValidWhenItMatchesTheNameGrammarProduction(string name, bool expected)
    {
        await Assert.That(NameUtils.IsNameValid(name)).IsEqualTo(expected);
    }
}
