<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>


  <ItemGroup>
    <PackageReference Include="JetBrains.Annotations" Version="2026.2.0" PrivateAssets="All" />
  </ItemGroup>

  <!-- Lexer isn't CLS compliant thus neither should be the assembly.  -->
  <ItemGroup>
    <AssemblyAttribute Include="CLSCompliantAttribute">
      <_Parameter1>false</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="XlsxSharp.Parser.Tests" />
    <InternalsVisibleTo Include="XlsxSharp.Benchmarks" />
  </ItemGroup>
</Project>
