<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Antlr4.Runtime.Standard" Version="4.13.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\XlsxSharp.Parser\XlsxSharp.Parser.csproj" />
  </ItemGroup>
</Project>
