using System.IO.Packaging;
using XlsxSharp.Excel;
using XlsxSharp.IO.Packaging;

namespace XlsxSharp.Tests.IO.Packaging;

/// <summary>
/// Checks the packaging layer against <see cref="System.IO.Packaging"/>, the OPC implementation
/// that ships with .NET and shares no code with it: on Excel's own files and on what XlsxSharp
/// writes, both have to see the same parts, content types and relationships, and what the layer
/// writes has to stay readable by both.
/// </summary>
public class OpcPackageInteropTests
{
    private const string GeneratedWorkbook = "(generated by XlsxSharp)";

    internal static IEnumerable<string> Packages =>
        [GeneratedWorkbook, .. OoxmlPartTypeCorpusTests.ExcelAuthoredFiles];

    [Test]
    [MethodDataSource(nameof(Packages))]
    public void SeesTheSamePartsAndContentTypes(string file)
    {
        using MemoryStream stream = Load(file);

        string[] expected;
        using (Package independent = Package.Open(stream, FileMode.Open, FileAccess.Read))
        {
            expected = [.. PartsOf(independent)];
        }

        stream.Position = 0;
        using OpcPackage package = OpcPackage.Open(stream);
        string[] actual = [.. package.Parts.Select(p => $"{p.Name} {p.ContentType}")];

        AssertSameLines(expected, actual);
    }

    /// <summary>
    /// The corpus's malformed_uri files carry hyperlink targets <see cref="Uri"/> cannot parse.
    /// The layer reads them - an external target is only ever passed through - but
    /// System.IO.Packaging throws on them, so there is nothing to compare against.
    /// </summary>
    internal static IEnumerable<string> PackagesWithParseableTargets =>
        Packages.Where(p => !p.Contains("malformed_uri", StringComparison.Ordinal));

    [Test]
    [MethodDataSource(nameof(PackagesWithParseableTargets))]
    public void ResolvesTheSameRelationships(string file)
    {
        using MemoryStream stream = Load(file);

        List<string> expected = [];
        using (Package independent = Package.Open(stream, FileMode.Open, FileAccess.Read))
        {
            expected.AddRange(
                independent.GetRelationships().Select(r => Describe(string.Empty, r))
            );
            foreach (PackagePart part in independent.GetParts().Where(p => !IsRelationshipPart(p)))
            {
                expected.AddRange(
                    part.GetRelationships().Select(r => Describe(part.Uri.OriginalString, r))
                );
            }
        }

        stream.Position = 0;
        using OpcPackage package = OpcPackage.Open(stream);
        List<string> actual = [.. package.Relationships.Select(r => DescribeOwn(string.Empty, r))];
        foreach (OpcPart part in package.Parts)
        {
            actual.AddRange(part.Relationships.Select(r => DescribeOwn(part.Name, r)));
        }

        AssertSameLines(expected, actual);

        static string Describe(string source, PackageRelationship relationship) =>
            relationship.TargetMode == TargetMode.External
                ? $"{source} {relationship.Id} {relationship.RelationshipType} external"
                : $"{source} {relationship.Id} {relationship.RelationshipType} {PackUriHelper.ResolvePartUri(relationship.SourceUri, relationship.TargetUri)}";

        static string DescribeOwn(string source, OpcRelationship relationship) =>
            relationship.TargetMode == OpcTargetMode.External
                ? $"{source} {relationship.Id} {relationship.RelationshipType} external"
                : $"{source} {relationship.Id} {relationship.RelationshipType} {relationship.TargetPartName}";
    }

    [Test]
    [MethodDataSource(nameof(Packages))]
    public void APackageRewrittenByTheLayerStaysReadableByAnotherImplementation(string file)
    {
        using MemoryStream original = Load(file);

        using MemoryStream rewritten = new();
        using (OpcPackage package = OpcPackage.Open(original, writable: true))
        {
            package.SaveTo(rewritten);
        }

        original.Position = 0;
        rewritten.Position = 0;
        using Package before = Package.Open(original, FileMode.Open, FileAccess.Read);
        using Package after = Package.Open(rewritten, FileMode.Open, FileAccess.Read);

        AssertSameLines([.. PartsOf(before)], [.. PartsOf(after)]);
    }

    [Test]
    public void APackageRewrittenByTheLayerStaysReadableByXlsxSharp()
    {
        using MemoryStream original = Load(GeneratedWorkbook);

        using MemoryStream rewritten = new();
        using (OpcPackage package = OpcPackage.Open(original, writable: true))
        {
            package.SaveTo(rewritten);
        }

        rewritten.Position = 0;
        using XLWorkbook workbook = new(rewritten);

        IXLWorksheet worksheet = workbook.Worksheet("Data");
        ClassicAssert.AreEqual("Hello", worksheet.Cell("A1").GetString());
        ClassicAssert.AreEqual(42, worksheet.Cell("B1").GetDouble());
    }

    /// <summary>
    /// The parts of a package as <see cref="System.IO.Packaging"/> sees them, minus the
    /// relationship parts it lists alongside the others and the layer keeps to itself.
    /// </summary>
    private static IEnumerable<string> PartsOf(Package package) =>
        package
            .GetParts()
            .Where(p => !IsRelationshipPart(p))
            .Select(p => $"{p.Uri.OriginalString} {p.ContentType}");

    private static bool IsRelationshipPart(PackagePart part) =>
        part.ContentType == "application/vnd.openxmlformats-package.relationships+xml";

    /// <summary>Compares two unordered sets of lines and names the ones that differ.</summary>
    private static void AssertSameLines(IEnumerable<string> expected, IEnumerable<string> actual)
    {
        HashSet<string> expectedSet = new(expected, StringComparer.OrdinalIgnoreCase);
        HashSet<string> actualSet = new(actual, StringComparer.OrdinalIgnoreCase);
        string[] missing = [.. expectedSet.Except(actualSet)];
        string[] extra = [.. actualSet.Except(expectedSet)];

        ClassicAssert.IsTrue(
            missing.Length == 0 && extra.Length == 0,
            "only System.IO.Packaging sees:"
                + Environment.NewLine
                + string.Join(Environment.NewLine, missing)
                + Environment.NewLine
                + "only OpcPackage sees:"
                + Environment.NewLine
                + string.Join(Environment.NewLine, extra)
        );
    }

    private static MemoryStream Load(string file)
    {
        MemoryStream stream = new();
        if (file == GeneratedWorkbook)
        {
            // Enough to exercise several parts and both package and part level relationships.
            using XLWorkbook workbook = new();
            IXLWorksheet worksheet = workbook.AddWorksheet("Data");
            worksheet.Cell("A1").Value = "Hello";
            worksheet.Cell("B1").Value = 42;
            worksheet.Cell("A2").Style.Fill.BackgroundColor = XLColor.Red;
            worksheet.Cell("A3").SetHyperlink(new XLHyperlink(new Uri("https://example.com")));
            workbook.Properties.Author = "XlsxSharp";
            workbook.SaveAs(stream);
        }
        else
        {
            using Stream resource = TestHelper.GetStreamFromResource(
                TestHelper.GetResourcePath(file)
            );
            resource.CopyTo(stream);
        }

        stream.Position = 0;
        return stream;
    }
}
